image: node:8.10.0

pages:
  cache:
    paths:
    - node_modules/

  script:
  - npm install gulp -g
  - npm install
  - gulp build
  - mv dist public
  artifacts:
    paths:
    - public
  only:
    - master